#ifndef __GIT_VERSION_H__
#define __GIT_VERSION_H__
#define GIMP_GIT_VERSION "GIMP_2_10_4-278-g0a8173ffde"
#define GIMP_GIT_VERSION_ABBREV "0a8173ffde"
#define GIMP_GIT_LAST_COMMIT_YEAR "2018"
#endif /* __GIT_VERSION_H__ */
