.TH GIMP 1
.SH NAME
gimp \- General Image Manipulation Program
.SH SYNOPSIS
.B gimp
.I "files ..."
.SH "DESCRIPTION"
This manual page was written for the Debian GNU/Linux distribution
(but may be used by others), because the original program does not
have a manual page.
Instead, it has documentation in the GNU Info(1) format which you can
access via "info
.B gimp".
.SH AUTHOR
This manual page was written by Rob Browning <osiris@cs.utexas.edu>,
for the Debian GNU/Linux system.
