#!/bin/sh -e
                                                                                
ver=2.0
prio=50

if [ "$1" = "configure" ]; then
	update-alternatives \
        --install /usr/bin/gimptool gimptool /usr/bin/gimptool-$ver $prio \
			--slave /usr/share/man/man1/gimptool.1.gz gimptool.1.gz \
				/usr/share/man/man1/gimptool-$ver.1.gz
				
# If the gimptool symlink doesn't exist, something broke, so this should fix:
	[ -L /usr/bin/gimptool ] || update-alternatives --auto gimptool
fi

#DEBHELPER#

