
/* NOTE: This file is auto-generated from authors.xml, do not edit it. */

static const gchar * const authors[] =
{
  "Spencer Kimball",
  "Peter Mattis",
  "Henrik Brix Andersen",
  "Hans Breuer",
  "Simon Budig",
  "João S. O. Bueno Calligaris",
  "Seth Burgess",
  "Stephane Chauveau",
  "Zbigniew Chyla",
  "David Costanzo",
  "Jay Cox",
  "Kevin Cozens",
  "Karine Delvare",
  "Daniel Egger",
  "Pedro Alonso Ferrer",
  "Piotr Filiciak",
  "Shlomi Fish",
  "Sylvain Foret",
  "Gerald Friedland",
  "Daniel Richard G",
  "GG",
  "Saul Goode",
  "David Gowers",
  "Dov Grobgeld",
  "Michael Hammel",
  "Robert Helgesson",
  "Kristian Jantz",
  "Róman Joost",
  "Geert Jordaens",
  "Aurimas Juška",
  "Øyvind Kolås",
  "Robert L Krawitz",
  "Eric Lamarque",
  "Tobias Lenz",
  "Frederic Leroy",
  "Adrian Likins",
  "Tor Lillqvist",
  "Kjartan Maraas",
  "Loren Merritt",
  "Chris Mohler",
  "Chris Moller",
  "Adam D Moss",
  "Michael Natterer",
  "David Neary",
  "Sven Neumann",
  "Martin Nordholts",
  "David Odin",
  "Robert Ögren",
  "Akkana Peck",
  "Raphaël Quinet",
  "Maurits Rijk",
  "Clarence Risher",
  "Guillermo S. Romero",
  "Michael Schumacher",
  "Jernej Simončič",
  "Manish Singh",
  "Mukund Sivaraman",
  "William Skaggs",
  "Kevin Sookocheff",
  "Jakub Steiner",
  "Nathan Summers",
  "Owen Taylor",
  "Patrice Tremblay",
  "Helvetix Victorinox",
  "Matthew Wilson",
  "Karl Günter Wünsch",
  NULL
};

static const gchar * const artists[] =
{
  "Lapo Calamandrei",
  "Karl La Rocca",
  "Andreas Nilsson",
  "Carol Spears",
  "Jakub Steiner",
  "William Szilveszter",
  NULL
};

static const gchar * const documenters[] =
{
  "Marco Ciampa",
  "Dust",
  "Ulf-D. Ehlert",
  "Alessandro Falappa",
  "Jakub Friedl",
  "Michael Hammel",
  "Julien Hardelin",
  "Róman Joost",
  "Hans de Jonge",
  "Semka Kuloviæ-Debals",
  "Manuel Quiñones",
  "Nickolay V. Shmyrev",
  "Axel Wernicke",
  NULL
};
